# Generated by Django 4.2.1 on 2023-05-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_author_alter_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['pubdate']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pubdate']},
        ),
    ]
